### ISSUE TITLE
Calling an embedded Navigator results in a new http request

### ISSUE THREAD

**Issue by tspng** [deontologician/restnavigator#39]
Hi

I think I discovered a bug but maybe it's the expected behaviour, I'm not sure.

When you call (execute) a Navigator (not orphaned) that was created from an embedded resource, a new http request is being made. Even though the navigator's state is already present.

I'm happy to provide a CR if this is seems to be a bug.

Cheers.

**Comment by deontologician** [comment]
Hi @haestan,

What are the semantics of the embedded resource? Does it have a self link or not?

If it has a self link, then just doing `N()` should not send an http request (but `N.fetch()` should)

If it doesn't have a self link, then `N()` should not send a request ever (since it has no url of its own).

I'm assuming this is a straightforward bug where it's just ignoring the cached state and sending the request no matter what. If that's the case, then a CR would be great

**Comment by tspng** [comment]
Seems to be a bug. Added a new CR #40

**Comment by deontologician** [comment]
Fixed in #40
